version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"

  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    ports:
      - "9093:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    build: ./producer
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer:/usr/src/app
    deploy:
      replicas: 5

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer:/usr/src/app
    deploy:
      replicas: 3
